FROM php:fpm-alpine

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions amqp bcmath bz2 calendar event exif gettext imagick imap json_post ldap memcached mysqli oauth odbc opcache pdo_mysql pdo_odbc pdo_pgsql pgsql redis soap sockets ssh2 xdebug xlswriter xmlrpc zip
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions gd
RUN IPE_ICU_EN_ONLY=1 install-php-extensions http intl mongodb
RUN install-php-extensions @composer
